function [pulse_data] = get_opto_pulse_data(data_folder, resp_win, psth_bins, artifact_win)
% function [PULSE_DATA] = get_opto_timing_data(DATA_FOLDER, RESP_WIN, PSTH_WINS, ARTIFACT_WIN)
% 
% Extracts opto pulse spikeing data summary for multiple experiment days in 
% a data folder. Use e.g. to get opto pulse experiment summary data for an 
% entire group of experiments as preparation for between-group comparisons.
% 
% INPUTS:
% 
% DATA_FOLDER: Full path to preprocessed data folder for opto pulse experiment
% (containing 1 or more folders with 1 or more pulse experiment preprocessed
% data files)
% 
% RESP_WIN: Response window for assessing opto response (i.e. for determining
% spike rate, finding peak response, assessing spike probability, etc.). 
% RESP_WIN can be 1 x 2 or N x 2 - if N x 2 the function will assess the 
% response in multiple response windows.
% 
% PSTH_BINS: Bins for a PSTH relative to opto onset, e.g. [-0.1:0.001:0.2]
% will generate a psth with 1 ms bins from 100 ms before to 200ms after the 
% stimulus.
% 
% ARTIFACT_WIN: Window that contains opto artifacts; Spikes that fall within 
% this window are effectively disregarded (set to NaN) for the purposes of 
% determining response measures.
% 
% OUTPUT:
% 
% PULSE_DATA is a struct with length equal to the number of experiment 
% folders. PULSE_DATA(N) is generated by OPTO_PULSE_FUNCTION; see the
% OPTO_PULSE_FUNCTION help for an explanation of the different fields of 
% the output struct.
% 

% Get directories from data_folder; remove non-experiment directories
expt_dirs                   = dir(data_folder);
expt_folders                = {expt_dirs.name};
qremove                     = ismember(expt_folders,{'.','..','.DS_Store'});
expt_folders(qremove)       = [];

% Loop over experiment folders
for a = 1:length(expt_folders)

    % Get opto pulse experiment spiking summary data for this experiment
    pulse_data(a)           = opto_pulse_function(fullfile(data_folder,expt_folders{a}), resp_win, psth_bins, artifact_win);

end
