function [drive_data] = get_opto_drive_data(data_folder, resp_win, psth_bins)
% function [DRIVE_DATA] = get_opto_drive_data(DATA_FOLDER, RESP_WIN, PSTH_BINS)
% 
% Extracts drive data for multiple experiment days in a data folder. Use
% e.g. to get drive experiment summary data for an entire group of
% experiments as preparation for between-group comparisons.
% 
% INPUTS:
% 
% DATA_FOLDER: Full path to preprocessed data folder for Drive experiment
% (containing 1 or more folders with 1 or more drive experiment preprocessed
% data files)
% 
% RESP_WIN: Response window for assessing whisker response (i.e. for determining
% spike rate, finding peak response, assessing spike probability, etc.). 
% 
% PSTH_BINS: Bins for a PSTH relative to whisker onset, e.g. [-0.1:0.001:0.2]
% will generate a psth with 1 ms bins from 100 ms before to 200ms after the stimulus.
% 
% OUTPUT:
% 
% DRIVE_DATA is a struct with length equal to the number of experiment 
% folders, and each DRIVE_DATA(N) has field DRIVE_DATA.EXPERIMENT with
% length equal to the number of timing experiment data files in that folder.
% 
% Field DRIVE_DATA.EXPERIMENT is generated by DRIVE_FUNCTION; see the
% DRIVE_FUNCTION help for an explanation of the different elements of the 
% output.
% 

% Get directories from data_folder; remove non-experiment directories
expt_dirs                   = dir(data_folder);
expt_folders                = {expt_dirs.name};
qremove                     = ismember(expt_folders,{'.','..','.DS_Store'});
expt_folders(qremove)       = [];

% Loop over experiment folders
drive_data                 = struct;
for a = 1:length(expt_folders)
    
    % What is current folder?
    this_folder     = expt_folders{a};
    
    % Get full folder path
    fullfolder      = fullfile(data_folder, this_folder);
    
    % What experiment data files (with extension '.mat') are in this folder?
    this_exp_files  = dir([fullfolder '/*.mat']);
    
    % Loop over experiment data files
    for b = 1:length(this_exp_files)
        
        % Get this data file name
        this_expt_name                  = this_exp_files(b).name;
        
        % Load preprocessed data file
        disp(['Loading ' this_expt_name '...'])
        load(fullfile(fullfolder, this_expt_name));
        
        % Use drive_function to extract summary data about this drive experiment
        drive_data(a).experiment(b)    = drive_function(ephys_data, resp_win, psth_bins);

    end
end
