function [timing_data] = get_opto_timing_data(data_folder, resp_win, psth_bins)
% function [TIMING_DATA] = get_opto_timing_data(DATA_FOLDER, RESP_WIN, PSTH_BINS)
% 
% Extracts timing data for multiple experiment days in a data folder. Use
% e.g. to get timing experiment summary data for an entire group of
% experiments as preparation for between-group comparisons.
% 
% INPUTS:
% 
% DATA_FOLDER: Full path to preprocessed data folder for Timing experiment
% (containing 1 or more folders with 1 or more timing experiment preprocessed
% data files)
% 
% RESP_WIN: Response window for assessing whisker response (i.e. for determining
% spike rate, finding peak response, assessing spike probability, etc.). 
% 
% PSTH_BINS: Bins for a PSTH relative to whisker onset, e.g. [-0.1:0.001:0.2]
% will generate a psth with 1 ms bins from 100 ms before to 200ms after the stimulus.
% 
% OUTPUT:
% 
% TIMING_DATA is a struct with length equal to the number of experiment 
% folders, and each TIMING_DATA(N) has field TIMING_DATA.EXPERIMENT with
% length equal to the number of timing experiment data files in that folder.
% 
% Field TIMING_DATA.EXPERIMENT is generated by TIMING_FUNCTION; see the
% TIMING_FUNCTION help for an explanation of the different elements of the 
% output.
% 

% Get directories from data_folder; remove non-experiment directories
expt_dirs                   = dir(data_folder);
expt_folders                = {expt_dirs.name};
qremove                     = ismember(expt_folders,{'.','..','.DS_Store'});
expt_folders(qremove)       = [];

% Loop over experiment folders
timing_data                 = struct;
for a = 1:length(expt_folders)
    
    % What is current folder?
    this_folder     = expt_folders{a};
    
    % Get full folder path
    fullfolder      = fullfile(data_folder, this_folder);
    
    % What experiment data files (with extension '.mat') are in this folder?
    this_exp_files  = dir([fullfolder '/*.mat']);
    
    % Loop over experiment data files
    for b = 1:length(this_exp_files)
        
        % Get this data file name
        this_expt_name                  = this_exp_files(b).name;
        
        % Load preprocessed data file
        disp(['Loading ' this_expt_name '...'])
        load(fullfile(fullfolder, this_expt_name));
        
        % Use timing_function to extract summary data about this timing experiment
        timing_info     = timing_function(ephys_data, resp_win, psth_bins);
        
        LFPs            = ephys_data.conditions(end).LFP_trace;
        LFP_times       = [1:length(LFPs)] / 1000 - ephys_data.conditions(end).whisk_onset; % relative to whisker onset at 1s
        LFP_resp_win    = [0.01 0.05]; % 10ms and 50ms
        chan_lims       = [4 16];
        smooth_win      = 3;
        max_LFP_sink    = get_max_sink(ephys_data.conditions(1).LFP_trace,LFP_times,LFP_resp_win,chan_lims,smooth_win)
        
        timing_info.L4_sink = max_LFP_sink;
        
        %%
        L5_chans        = max_LFP_sink + 3:12;
        L23_chans       = 1:max_LFP_sink - 2;
        
        timing_multi_data 	= timing_results(ephys_data,L5_chans);
        
        
        timing_info.opto_rate    = timing_multi_data.control_opto_rate;
        timing_info.opto_stds    = timing_multi_data.control_opto_stds;
        timing_info.opto_p       = timing_multi_data.opto_response_p;
        timing_info.opto_power   = ephys_data.conditions(end).LED_power;
        timing_info.L5_chans     = L5_chans;
        timing_info.L23_chans    = L23_chans;
        
        %%
        
        timing_data(a).experiment(b)  = timing_info;
    end
end
