function [timing_data] = get_opto_timing_data(data_folder, resp_win, psth_bins)
% function [TIMING_DATA] = get_opto_timing_data(DATA_FOLDER, RESP_WIN, PSTH_BINS)
% 
% Extracts timing data for multiple experiment days in a data folder. Use
% e.g. to get timing experiment summary data for an entire group of
% experiments as preparation for between-group comparisons.
% 
% TIMING_DATA is a struct with length equal to the number of experiment 
% folders, and each TIMING_DATA(N) has field TIMING_DATA.EXPERIMENT with
% length equal to the number of timing experiment data files in that folder.
% 
% Field TIMING_DATA.EXPERIMENT is generated by TIMING_FUNCTION; see the
% TIMING_FUNCTION help for an explanation of the different elements of the 
% output.

% Get directories from data_folder; remove non-experiment directories
expt_dirs                   = dir(data_folder);
expt_folders                = {expt_dirs.name};
qremove                     = ismember(expt_folders,{'.','..','.DS_Store'});
expt_folders(qremove)       = [];

% Loop over experiment folders
timing_data                 = struct;
for a = 1:length(expt_folders)
    
    % What is current folder?
    this_folder     = expt_folders{a};
    
    % Get full folder path
    fullfolder      = fullfile(data_folder, this_folder);
    
    % What experiment data files (with extension '.mat') are in this folder?
    this_exp_files  = dir([fullfolder '/*.mat']);
    
    % Loop over experiment data files
    for b = 1:length(this_exp_files)
        
        % Get this data file name
        this_expt_name                  = this_exp_files(b).name;
        
        % Load preprocessed data file
        disp(['Loading ' this_expt_name '...'])
        load(fullfile(fullfolder, this_expt_name));
        
        % Use timing_function to extract summary data about this timing experiment
        timing_data(a).experiment(b)    = timing_function(ephys_data, resp_win, psth_bins);

    end
end
